{
  "Elements": [
    {
      "ElementType": 2,
      "Indexes": [
        0,
        10,
        6
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        3,
        7,
        11
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        6,
        0,
        11
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        8,
        1,
        9
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        10,
        8,
        6
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        6,
        4,
        9
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        7,
        6,
        5
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        10,
        7,
        5
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        11,
        7,
        10
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        7,
        6,
        2
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        11,
        6,
        7
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        9,
        8,
        6
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        8,
        6,
        5
      ]
    }
  ],
  "Coords": [
    {
      "Point3d": [
        -2,
        -1,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        2,
        -1,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        2,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        -2,
        1,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        2,
        1,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        -2,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0.666666666666667,
        1,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        -0.6666666666666665,
        1,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0.6666666666666665,
        -1.0000000000000002,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        1.3333333333333335,
        0,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        -0.6666666666666667,
        -0.9999999999999999,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        -1.3333333333333333,
        0,
        0
      ],
      "Removed": false
    }
  ],
  "Base": {
    "Name": "",
    "Groups": null
  }
}