{
  "Elements": [
    {
      "ElementType": 1,
      "Indexes": [
        0,
        1
      ]
    },
    {
      "ElementType": 3,
      "Indexes": [
        2,
        3,
        4,
        5
      ]
    }
  ],
  "Coords": [
    {
      "Point3d": [
        -2,
        0,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        2,
        0,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        4,
        4
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        4,
        -4
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        -4,
        -4
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        -4,
        4
      ],
      "Removed": false
    }
  ],
  "Groups": {
    "Data": "{\"Index\":10000,\"Data\":\"{\\\"Name\\\":\\\"\\\",\\\"Datas\\\":null}\"}"
  }
}