{
  "Elements": [
    {
      "ElementType": 2,
      "Indexes": [
        0,
        3,
        2
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        3,
        4,
        5
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        3,
        0,
        1
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        3,
        5,
        2
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        4,
        3,
        1
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        4,
        1,
        2
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        5,
        4,
        2
      ]
    }
  ],
  "Coords": [
    {
      "Point3d": [
        -2,
        -1,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        2,
        -1,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        2,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        -1,
        -0.5,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        1,
        -0.5,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        1,
        0
      ],
      "Removed": false
    }
  ]
}