{
  "Elements": [
    {
      "ElementType": 1,
      "Indexes": [
        0,
        5
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        2,
        5,
        4
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        5,
        6
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        5,
        3,
        6
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        6,
        1
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        6,
        5,
        4
      ]
    }
  ],
  "Coords": [
    {
      "Point3d": [
        0,
        -5,
        -5
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        5,
        5
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        -1,
        -3
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        -1,
        3
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        3,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        -0.9999999999999998,
        -0.9999999999999998
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        1.2857142857142856,
        1.2857142857142856
      ],
      "Removed": false
    }
  ],
  "Base": {
    "Name": "",
    "Groups": null
  }
}