{
  "Elements": [
    {
      "ElementType": 2,
      "Indexes": [
        0,
        3,
        7
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        3,
        2,
        7
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        3,
        0,
        1
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        3,
        1,
        6
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        7,
        3,
        2
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        2,
        3,
        6
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        2,
        4,
        5
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        7,
        2,
        5
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        6,
        3,
        2
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        6,
        2,
        4
      ]
    }
  ],
  "Coords": [
    {
      "Point3d": [
        -2,
        -1,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        2,
        -1,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        2,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        0,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        3,
        5,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        -3,
        5,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0.631578947368421,
        1.0526315789473684,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        -0.6315789473684214,
        1.052631578947369,
        0
      ],
      "Removed": false
    }
  ],
  "Base": {
    "Name": "",
    "Groups": null
  }
}