{
  "Elements": [
    {
      "ElementType": 1,
      "Indexes": [
        0,
        1
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        2,
        3
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        0,
        2
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        1,
        3
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        0,
        2,
        1
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        2,
        1,
        3
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        4,
        5
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        2,
        4
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        3,
        5
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        2,
        4,
        3
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        4,
        3,
        5
      ]
    }
  ],
  "Coords": [
    {
      "Point3d": [
        0,
        0,
        0.5
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        0,
        2.5
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0.24999999999999997,
        0.2,
        0.43301270189221935
      ],
      "Removed": false
    },
    {
      "Point3d": [
        1.2499999999999998,
        0.2,
        2.165063509461097
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0.4330127018922193,
        0.4,
        0.25000000000000006
      ],
      "Removed": false
    },
    {
      "Point3d": [
        2.1650635094610964,
        0.4,
        1.2500000000000002
      ],
      "Removed": false
    }
  ]
}