{
  "Elements": [
    {
      "ElementType": 2,
      "Indexes": [
        1,
        0,
        3
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        0,
        1,
        2
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        0,
        2,
        3
      ]
    }
  ],
  "Coords": [
    {
      "Point3d": [
        0,
        0,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        -1,
        -1,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        1,
        -1,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        5,
        0
      ],
      "Removed": false
    }
  ],
  "Base": {
    "Name": "",
    "Groups": null
  }
}