{
  "Elements": [
    {
      "ElementType": 1,
      "Indexes": [
        0,
        6
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        2,
        9
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        0,
        12
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        1,
        15
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        0,
        12,
        6
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        2,
        1,
        9
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        4,
        18
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        2,
        21
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        3,
        24
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        2,
        21,
        9
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        4,
        3,
        18
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        6,
        7
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        7,
        8
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        8,
        1
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        9,
        10
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        10,
        11
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        11,
        3
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        12,
        13
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        13,
        14
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        14,
        2
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        15,
        16
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        16,
        17
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        17,
        3
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        18,
        19
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        19,
        20
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        20,
        5
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        21,
        22
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        22,
        23
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        23,
        4
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        24,
        25
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        25,
        26
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        26,
        5
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        6,
        2,
        7
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        12,
        13,
        6
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        9,
        1,
        10
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        9,
        4,
        10
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        21,
        22,
        9
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        18,
        3,
        19
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        7,
        2,
        8
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        13,
        14,
        6
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        10,
        1,
        11
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        10,
        4,
        11
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        22,
        23,
        9
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        19,
        3,
        20
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        8,
        2,
        1
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        14,
        2,
        6
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        11,
        1,
        15
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        11,
        4,
        3
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        23,
        4,
        9
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        20,
        3,
        24
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        15,
        11,
        16
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        24,
        20,
        25
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        16,
        11,
        17
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        25,
        20,
        26
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        17,
        11,
        3
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        26,
        20,
        5
      ]
    }
  ],
  "Coords": [
    {
      "Point3d": [
        0,
        0,
        0.5
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        0,
        2.5
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0.24999999999999997,
        0.2,
        0.43301270189221935
      ],
      "Removed": false
    },
    {
      "Point3d": [
        1.2499999999999998,
        0.2,
        2.165063509461097
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0.4330127018922193,
        0.4,
        0.25000000000000006
      ],
      "Removed": false
    },
    {
      "Point3d": [
        2.1650635094610964,
        0.4,
        1.2500000000000002
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        0,
        1
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        0,
        1.5
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        0,
        2
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0.4999999999999999,
        0.2,
        0.8660254037844387
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0.7499999999999999,
        0.2,
        1.299038105676658
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0.9999999999999998,
        0.2,
        1.7320508075688774
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0.06249999999999999,
        0.05,
        0.48325317547305485
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0.12499999999999999,
        0.1,
        0.4665063509461097
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0.18749999999999997,
        0.15000000000000002,
        0.4497595264191645
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0.31249999999999994,
        0.05,
        2.4162658773652743
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0.6249999999999999,
        0.1,
        2.3325317547305486
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0.9374999999999998,
        0.15000000000000002,
        2.2487976320958225
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0.8660254037844386,
        0.4,
        0.5000000000000001
      ],
      "Removed": false
    },
    {
      "Point3d": [
        1.299038105676658,
        0.4,
        0.7500000000000002
      ],
      "Removed": false
    },
    {
      "Point3d": [
        1.7320508075688772,
        0.4,
        1.0000000000000002
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0.2957531754730548,
        0.25,
        0.3872595264191645
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0.34150635094610965,
        0.30000000000000004,
        0.3415063509461097
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0.3872595264191645,
        0.35000000000000003,
        0.2957531754730549
      ],
      "Removed": false
    },
    {
      "Point3d": [
        1.4787658773652739,
        0.25,
        1.9362976320958227
      ],
      "Removed": false
    },
    {
      "Point3d": [
        1.7075317547305482,
        0.30000000000000004,
        1.7075317547305486
      ],
      "Removed": false
    },
    {
      "Point3d": [
        1.9362976320958223,
        0.35000000000000003,
        1.4787658773652743
      ],
      "Removed": false
    }
  ],
  "Groups": {
    "Data": "{\"Index\":10000,\"Data\":\"{\\\"Name\\\":\\\"Part of spiral\\\",\\\"Datas\\\":[\\\"{\\\\\\\"Index\\\\\\\":80,\\\\\\\"Data\\\\\\\":\\\\\\\"{\\\\\\\\\\\\\\\"Name\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\"typical spiral with split\\\\\\\\\\\\\\\"}\\\\\\\"}\\\"]}\"}"
  }
}