{
  "Elements": [
    {
      "ElementType": 2,
      "Indexes": [
        0,
        3,
        5
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        3,
        1,
        4
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        5,
        3,
        2
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        4,
        3,
        2
      ]
    }
  ],
  "Coords": [
    {
      "Point3d": [
        0,
        0,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        2,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        2,
        2,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        1,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        1,
        2,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        1,
        1,
        0
      ],
      "Removed": false
    }
  ],
  "Groups": {
    "Data": "{\"Index\":10000,\"Data\":\"{\\\"Name\\\":\\\"\\\",\\\"Datas\\\":null}\"}"
  }
}