{
  "Elements": [
    {
      "ElementType": 1,
      "Indexes": [
        0,
        5
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        2,
        5,
        4
      ]
    },
    {
      "ElementType": 1,
      "Indexes": [
        5,
        1
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        5,
        2,
        3
      ]
    },
    {
      "ElementType": 2,
      "Indexes": [
        5,
        3,
        4
      ]
    }
  ],
  "Coords": [
    {
      "Point3d": [
        -2,
        0,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        2,
        0,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        -1,
        -3
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        -1,
        3
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        3,
        0
      ],
      "Removed": false
    },
    {
      "Point3d": [
        0,
        0,
        0
      ],
      "Removed": false
    }
  ]
}